viz = audioviz.new({ 1600, 900 }, 'Music/koji kuga [bJK7fNwpRmU].mp3')
viz:set_text_font('/usr/share/fonts/TTF/Iosevka-Regular.ttc')
viz:add_default_effects()
viz:set_background('/home/t/.wallpaper.jpg')
viz:set_timing_text_enabled(true)
start_in_window(viz)
-- encode(viz, 'out.mp4', 60, 'h264_vaapi', 'copy')